data:
  data_root: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D"                                      # Root directory for data
  text_dir: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/texts"                                 # Directory with positive (real) text .txt files
  negative_text_dir: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/neg_texts"                    # Directory with negative-swapped .txt files
  motion_babel_json: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/motion_babel.json"            # Path to motion-babel json file
  babel_caption_json: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/babel_caption.json"          # Path to babel-caption json file
  max_text_length: 60                                                                             # Max token length for CLIP
  num_other_negatives: 3                                                                          # How many captions from other BABEL label groups
  num_other_positives: 3                                                                          # How many captions from the same BABEL label group
  random_seed: 42
  # sp-motionclip
model:
  pretrained_name: "openai/clip-vit-base-patch32"                                                 # Which CLIP to load
  ckpt_path: "/home/jiaxu/projects/sp-motionclip/tune/laclip/laion400m_laclip.pt"                 # Which checkpoint to load
  dropout: 0.1

loss:
  margin: 0.2
  alpha1: 1.0
  alpha2: 1.0
  alpha3: 1.0
  alpha4: 1.0

train:
  batch_size: 32
  num_workers: 8
  learning_rate: 5e-5
  weight_decay: 0.01
  num_epochs: 16
  scheduler_factor: 0.5
  scheduler_patience: 5

checkpoint:
  save_path: "/scratch/izar/jiaxu/ckpts/text_encoder"
  save_every: 1                                                                                   # Save checkpoint every 'save_every' epochs