data:
  json_path: "/home/jiaxu/projects/sp-motionclip/viz/eval.json"
  max_length: 64
  random_seed: 42

model:
  pretrained_name: "distilbert-base-uncased"
  dropout: 0.1
  use_mean_pooling: true  

train:
  batch_size: 1
  num_workers: 2
  learning_rate: 5e-5
  weight_decay: 0.01
  num_epochs: 5
  margin: 3
  num_negatives: 5   

checkpoint:
  save_path: "./checkpoints"
