device: "cuda"                                                                      # Use "cpu" if no GPU is available

data:
  # data_root: "/home/jiaxu/projects/sp-motionclip/dataset/HumanML3D"                        # Root directory for data
  # motion_dir: "/home/jiaxu/projects/sp-motionclip/dataset/HumanML3D/new_joint_vecs"        # Directory containing motion .npy files
  # text_dir: "/home/jiaxu/projects/sp-motionclip/dataset/HumanML3D/texts"                   # Directory containing text .txt files
  # negative_text_dir: "/home/jiaxu/projects/sp-motionclip/dataset/HumanML3D/neg_texts"      # Directory containing event text .json files
  data_root: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D"                        # Root directory for data
  motion_dir: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/new_joint_vecs"        # Directory containing motion .npy files
  text_dir: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/texts"                   # Directory containing text .txt files
  negative_text_dir: "/home/jiaxu/projects/sp-mdm/dataset/HumanML3D/neg_texts"      # Directory containing event text .json files
  min_motion_length: 40                                                             # Minimum number of frames in motion data, i.e., 2s
  max_motion_length: 200                                                            # Maximum number of frames in motion data, i.e., 10s
  max_shuffled_texts: 5                                                             # Maximum number of shuffled texts to use for training
  max_text_length: 60                                                               # Maximum number of words in text data
  n_joints: 22                                                                      # Number of joints in the motion data
  n_feats: 263                                                                      # Number of features per joint (e.g., x, y, z, velocity_x, velocity_y, velocity_z)
  random_seed: 42                                                                   # Random seed for reproducibility

train:
  batch_size: 32                                                                    # Batch size for training
  shuffle: true                                                                     # Shuffle the training data
  num_workers: 4                                                                    # Number of subprocesses for data loading
  learning_rate: 5e-5                                                               # Learning rate for optimizer, 1e-4
  weight_decay: 1e-4                                                                # Weight decay for optimizer, 1e-2
  num_epochs: 100                                                                   # Number of training epochs, 300
  scheduler_factor: 0.5                                                             # Factor by which to reduce the learning rate
  scheduler_patience: 3                                                             # Number of epochs with no improvement after which learning rate will be reduced
  scheduler_min_lr: 1e-8                                                            # Minimum learning rate for the scheduler

model:
  motion_encoder: "transformer"                                                     # Type of motion encoder to use
  text_encoder: "laclip"                                                            # Type of text encoder to use
  latent_dim: 512                                                                   # Dimension of the latent space
  num_transformer_layers: 4                                                         # Number of transformer layers in motion encoder
  num_mamba_layers: 2                                                               # Number of MAMBA layers in motion encoder
  num_heads: 8                                                                      # Number of attention heads in motion encoder
  ff_size: 1024                                                                     # Feedforward size in motion encoder
  dropout: 0.1                                                                      # Dropout rate in motion encoder
  clip_model_name: "ViT-B/32"                                                       # CLIP model variant to use
  laclip_ckpt_path: "/home/jiaxu/projects/sp-motionclip/tune/laclip/laion400m_laclip.pt"                              # Path to the LA-CLIP model
  motionlaclip_ckpt_path: "/home/jiaxu/projects/sp-motionclip/tune/motionlaclip/BEST_dropout_coslr_FinetuneLaCLIP_DS_HumanML3D_LR_5e-05_WD_0.01_EP_16_y8ksv238/finetunelaclip_epoch_8.pth"                            # Path to the Motion-LA-CLIP model
  motionlaclipplus_ckpt_path: "/home/jiaxu/projects/sp-motionclip/tune/motionlaclipplus/FinetuneLaCLIP_Centroids_DS_BABEL&HumanML3D_LR_5e-05_WD_0.05_EP_16_ey24jqsx/finetunelaclip_epoch_13.pth"
  activation: "gelu"                                                                # Activation function in motion encoder

loss:
  temperature: 0.07                                                                 # Temperature parameter for contrastive loss
  margin: 2                                                                         # Margin parameter for contrastive loss

checkpoint:
  save_path: "/scratch/izar/jiaxu/ckpts/motion_encoder"                             # Directory to save model checkpoints
  save_every: 50                                                                    # Save checkpoint every 'save_every' epochs

test:
  ckpt: "/home/jiaxu/projects/sp-motionclip/tune/motion_encoder/BEST_dropout_coslr_FinetuneLaCLIP_DS_HumanML3D_LR_5e-05_WD_0.01_EP_16_y8ksv238/finetunelaclip_epoch_8.pth"  # Path to the model checkpoint
  batch_size: 256                                                                   # Batch size for testing
  num_workers: 4                                                                    # Number of subprocesses for data loading

